version: "2.0"
services:
  db:
    build: './mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop_hm
    ports:
      - "3306:3306"
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
  apache:
    build: './httpd'
    depends_on:
      - db
    ports:
      - "80:80"
    links:
      - db
    networks:
      - default
   



